/*
 * TMWindow.java
 *
 * Created on April 30, 2008, 2:44 PM
 */

package tminfogenerator;

import java.util.ArrayList;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.swing.JOptionPane;


/**
 *
 * @author  Administrator
 */
public class TMWindow extends javax.swing.JFrame {
    
    /** Creates new form TMWindow */
    public TMWindow() {
        initComponents();
        
    int delay = 1000 * 60 * 60 * 24 * 7;   // delay for 5 sec.
    int period = 1000 * 60 * 60 * 24 * 7;  // repeat every sec.
    Timer timer = new Timer();
    
    timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                //JOptionPane.showMessageDialog(null, "Here");
                forceSendButonMouseClicked(null);
                
            }
        }, delay, period);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        forceSendButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel1.setText("Telemarketer Info Generator");

        emailField.setText("jps330@gmail.com");

        jLabel2.setText("Email Address of Telemarketing Firm:");

        forceSendButon.setText("Force Send Report");
        forceSendButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forceSendButonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(forceSendButon)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forceSendButon))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forceSendButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forceSendButonMouseClicked
        if(emailField.getText().compareTo("")!=0)
        {
         try {
            String messageOut = "Himalaya.com Telemarketing Report\n*******************************************\n\n";
            
            DataBaseAccessor dba = new DataBaseAccessor();

            ArrayList<CustomerInfo> result = dba.getCustomerInfo();

            //JOptionPane.showMessageDialog(null, "" + result.size());
            
            for(int i=0;i<result.size();i++)
            {
                messageOut += "Client Name: "+result.get(i).getName()+"\n";
                messageOut += "Client Age: "+result.get(i).getAge()+"\n";
                messageOut += "Client Annual Income: "+result.get(i).getAnnualIncome()+"\n";
                messageOut += "Client Email: "+result.get(i).getEmail()+"\n";
                messageOut += "Client Gender: "+result.get(i).getGender()+"\n";
                messageOut += "Client Phone Number: "+result.get(i).getPhoneNumber()+"\n";
                messageOut += "Client Total Bids: "+result.get(i).getTotalBids()+"\n";
                
                for(int j=0;j<result.get(i).getAddress().size();j++)
                {
                    messageOut += "Client Address #"+(j+1)+": "+result.get(i).getAddress().get(j)+"\n";
                }
                messageOut +="\n\n\n";
            }
            
            
            

            SendEmail.sendMail(messageOut,emailField.getText());

            dba.closeConnection();
            
            JOptionPane.showMessageDialog(null, "Message Sent!");
            
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
        
    }//GEN-LAST:event_forceSendButonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TMWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JButton forceSendButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
